SF-3750: Explicit Data Includes
step-finance/solana pull request #8
Opened 2023-12-19 22:59 UTC by quellen-sol

2023-12-20 00:40 UTC, thesoftwarejedi requested changes
killin it

2023-12-20 00:40 UTC, thesoftwarejedi commented on core/src/banking_stage/committer.rs
> +            Bank, CommitTransactionCounts, PreOrPostDatum, TransactionBalancesSet, TransactionDatumSet,
for mergeability, put additions in a line by themselves

2023-12-20 00:40 UTC, thesoftwarejedi commented on core/src/banking_stage/consumer.rs
> +        bank::{Bank, LoadAndExecuteTransactionsOutput, PreOrPostDatum, TransactionCheckResult},
for mergeability, put additions on own line

2023-12-20 00:40 UTC, thesoftwarejedi commented on ledger/src/blockstore_processor.rs
> +            Bank, TransactionBalancesSet, TransactionDatumSet, TransactionExecutionDetails,
for mergeability, put additions on own line

2023-12-20 00:40 UTC, thesoftwarejedi commented on runtime/src/bank.rs
> +pub type ProgramDatumInclusions = HashMap<Pubkey, (bool, bool)>;
make a struct for the tuple; cuz why not

2023-12-20 00:40 UTC, thesoftwarejedi commented on runtime/src/bank.rs
> +        if !include_data || data.len() > STEP_TX_DATUM_MAX_SIZE || account.executable() {
lets kill this off too

2023-12-20 00:40 UTC, thesoftwarejedi commented on runtime/src/runtime_config.rs
>  /// Encapsulates flags that can be used to tweak the runtime behavior.
this isn't the right file.  theres a geyser config file that it reads somewhere somehow

2023-12-21 21:43 UTC, JamesMDunn approved these changes
🦀 🦀 🦀 🦀 🦀

2024-01-10 22:08 UTC, thesoftwarejedi approved these changes
Where is this data compressed?  Doesn't it zip it somewhere?  Is that in our plugin perhaps?
Looks good.

2024-01-10 22:09 UTC, thesoftwarejedi commented
I assume tested locally with our plugin with success.

2024-01-10 23:16 UTC, quellen-sol commented
> I assume tested locally with our plugin with success.

Yup tested with a local ingestooor and everything :+1:

2024-01-10 23:16 UTC, quellen-sol commented
> Where is this data compressed? Doesn't it zip it somewhere? Is that in our plugin perhaps? Looks good.

Plugin does it I think

2024-01-10 23:19 UTC, merged